# Sample Arbitrader configuration file
# Copy this file to "application.yaml" and fill out the settings that you want for your bot.
# When you run the JAR file, make sure the config file is in the current directory so it can be read.

# All the logs you see on the console will also be shipped to Slack.
notifications:
  slack:
    accessToken: x
    botAccessToken: x
    channel: x

trading:
  # The percentage difference between the "long" and "short" exchanges before we will open our positions.
  entrySpread: 0.0080

  # The percentage difference *in profit only* before we will close our positions.
  # Fees will be added to this amount.
  exitTarget: 0.0050

  # (Optional)
  # Specify the amount to use per trade. If this value is missing, the bot will default to 90% of the balance
  # of the exchange that has the smallest balance. Arbitrader's author highly recommends starting out the bot
  # with a fixedExposure around 10.00 to avoid risking much money at first.
  fixedExposure: 10.00

  # Connection information for each exchange goes in this list.
  #
  # To add a new exchange or remove one that you don't use, either add or remove the configuration from this list.
  # Arbitrader uses the XChange library to talk to exchanges, so you can try any of the 60+ exchanges implemented in
  # that project. Not all of them support all the features the bot needs, so you should be careful when you try out
  # a new exchange for the first time. If you can, consider submitting pull requests to XChange to add better support
  # for more exchanges!
  exchanges:
    -
      # This is the name of the class from XChange that implements the connection to the exchange.
      exchangeClass: org.knowm.xchange.kraken.KrakenExchange

      # The API key for Kraken.
      apiKey: x

      # The API secret for Kraken.
      secretKey: x

      # The pairs you wish to trade on Kraken.
      tradingPairs:
        - BTC/USD
        - BCH/USD
        - LTC/USD
        - EOS/USD
        - ADA/USD
        - XRP/USD
        - BSV/USD
        - XLM/USD
        - ETC/USD
        - XTZ/USD
        - DASH/USD
        - XMR/USD
        - GNO/USD
        - QTUM/USD
        - ETH/USD
        - REP/USD
        - ZEC/USD

      # Whether or not this exchange supports margin (aka. leveraged) trades. Kraken does.
      margin: true

      # Pairs to exclude from margin trading on Kraken
      # (i.e. because the exchange doesn't support margin for those pairs)
      marginExclude:
        - LTC/USD
        - EOS/USD
        - ADA/USD
        - BSV/USD
        - XLM/USD
        - ETC/USD
        - XTZ/USD
        - DASH/USD
        - XMR/USD
        - GNO/USD
        - QTUM/USD
        - REP/USD
        - ZEC/USD

      # The amount of fees Kraken charges. If an exchange's API supports requesting fees at runtime, the bot
      # will use that value instead. If not, it will fall back to the configured value.
      fee: 0.0026
    -
      exchangeClass: org.knowm.xchange.quoine.QuoineExchange
      apiKey: x
      secretKey: x

      tradingPairs:
        - BTC/USD
        - ETH/USD
        - XRP/USD
        - BCH/USD
        - QASH/USD
        - QTUM/USD
        - RKT/USD
        - NEO/USD
        - ONT/USD
        - DASH/USD

      # Quoine (Liquid) has a couple of custom parameters we need to pass in order to enable margin trading with the API.
      custom:
        Use_Margin: true
        Leverage_Level: 2
      margin: true
      marginExclude:
        - QASH/USD
        - QTUM/USD
        - RKT/USD
        - NEO/USD
        - ONT/USD
        - DASH/USD
      fee: 0.0020
    -
      exchangeClass: org.knowm.xchange.coinbasepro.CoinbaseProExchange
      apiKey: x
      secretKey: x

      # Coinbase Pro requires an additional "passphrase" for authentication to the API.
      custom:
        passphrase: x
      tradingPairs:
        - BTC/USD
        - LTC/USD
        - BCH/USD
        - ETH/USD
        - ETC/USD
        - ZRX/USD
      margin: false
      fee: 0.0030
    -
      exchangeClass: org.knowm.xchange.poloniex.PoloniexExchange
      apiKey: x
      secretKey: x
      tradingPairs:
        - BTC/USD
        - BCHSV/USD
        - LTC/USD
        - ETH/USD
        - XRP/USD
        - STR/USD
        - BCHABC/USD
        - XMR/USD
        - ZEC/USD
        - FOAM/USD
        - DOGE/USD
        - BCH/USD
      margin: false
      fee: 0.0025

      # Poloniex doesn't support any fiat currencies, so we need to use a USD based stablecoin instead.
      #
      # I've found USDC to be more true to USD than USDT, but you could also use a crypto like BTC here
      # if you wanted to do pure crypto trading with no fiat. Effectively this just aliases any xxx/USD
      # pair to xxx/USDC. If you put BTC here you could list ETH/USD and it would actually trade ETH/BTC.
      homeCurrency: USDC
    