notifications:
  slack:
    accessToken: x
    botAccessToken: x
    channel: channel

trading:
  entrySpread: 0.0080
  exitTarget: 0.0050
  fixedExposure: 100.00
  tradingPairs:
    - BTC/USD
    - ETH/USD
    - LTC/USD

  exchanges:
    -
      exchangeClass: org.knowm.xchange.kraken.KrakenExchange
      apiKey: x
      secretKey: x
      margin: true
      fee: 0.0026
    -
      exchangeClass: org.knowm.xchange.quoine.QuoineExchange
      apiKey: x
      secretKey: x
      custom:
        Use_Margin: true
        Leverage_Level: 2
      margin: true
      fee: 0.0020
    -
      exchangeClass: org.knowm.xchange.coinbasepro.CoinbaseProExchange
      apiKey: x
      secretKey: x
      custom:
        passphrase: x
      margin: false
      fee: 0.0030
    -
      exchangeClass: org.knowm.xchange.poloniex.PoloniexExchange
      apiKey: x
      secretKey: x
      margin: false
      fee: 0.0025
      homeCurrency: USDT
    