logging:
  level:
    si:
      mazi:
        rescu: ERROR
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  banner:
    image:
      location: src/main/resources/banner.txt
